# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Raygun RUM"
client_id = "641c4c653030ad1ca22a93c05d957568"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
