# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Raygun RUM"
client_id = "641c4c653030ad1ca22a93c05d957568"
application_url = "https://marketplace.raygun.com/external/shopify/connect/rum"
embedded = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://marketplace.raygun.com/external/shopify/redirect/rum"
]

[webhooks]
api_version = "2023-10"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://app.raygun.com"
  customer_data_request_url = "https://app.raygun.com"
  shop_deletion_url = "https://app.raygun.com"

[pos]
embedded = false
