# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Raygun Crash Reporting"
client_id = "242392a59ff87b609c4027eee44772c7"
application_url = "https://marketplace.raygun.com/external/shopify/connect/crashreporting"
embedded = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://marketplace.raygun.com/external/shopify/redirect/crashreporting"
]

[webhooks]
api_version = "2023-10"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://marketplace.raygun.com/shopify/webhook/crashreporting/customer/redact"
  customer_data_request_url = "https://marketplace.raygun.com/shopify/webhook/crashreporting/customer"
  shop_deletion_url = "https://marketplace.raygun.com/shopify/webhook/crashreporting/shop/redact"

[pos]
embedded = false
